FROM prevas/yocto-dev:latest


RUN apt-get -q update && apt-get -q install -y \
    -o Dpkg::Options::="--force-confnew" \
    --no-install-recommends \
    ripgrep fd-find tmux neovim fzf

WORKDIR /yocto
